### ISSUE TITLE
Give an easy navigation from edit to view

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#127]
**Is your feature request related to a problem? Please describe.**
A person editing a dashboard needs to hand modify the URL (or go back in browser history X-2X times, where X is the number of elements they edited) to go to the "view" view.

**Describe the solution you'd like**
Split the "Save Dashboard" button into "Save (keep editing)" and "Save (view)".

Or just make the "Save Dashboard" button save and the go to the view URL (which would be an easy browser "back" to get back to) 

**Describe alternatives you've considered**
Having a view mode within the edit screen seems like a lot of work and potential to click on links which would take you away from an unsaved dashboard.

An easy link from view to edit I think you could just add as an element button manually per dashboard (default dashboard?) if that was appropriate but I don't think appropriate for all, e.g. in installations where not everyone had rights to edit.

**Comment by davekempe** [comment]
I would also be in favour of a more continuous save in some fashion. There is probably a fairly simple solution to save every 10 seconds or so? Its not a lot of i/o? 
Then we can just have a view button.

**Comment by ollytom** [comment]
On Tue, Oct 25, 2022 at 03:38:53PM -0700, s2156945 wrote:
> **Is your feature request related to a problem? Please describe.**
> A person editing a dashboard needs to hand modify the URL (or go back in browser history X-2X times, where X is the number of elements they edited) to go to the "view" view.

Ah yeah this was driving me crazy. I fixed this in ac92146048947 by removing the client-side routing altogether so that it has predictable behaviour. It was pretty confusing; URL parameters were being used as a kind of state management to work out which element was selected. That's ok in isolation, but meerkat is using a preact "reducer" in memory for other parts of the UI.

I think the simplest thing we can do (with no extra javascript!) is have a button "Save & view":

	<a
		class="btn btn-success"
		href="/my-dashboard/view"
		onClick=meerkat.saveDashboard(...)
	>
		Save & view
	</a>

> I would also be in favour of a more continuous save in some fashion.
> There is probably a fairly simple solution to save every 10 seconds or so? Its not a lot of i/o?

There's a race condition here - how often is often enough? - but I don't know how to solve it without some clever react stuff. I think that HTML tag above is really dumb, clear, and easy to maintain. Even with an event-driven autosave thing, or just a 5-second autosave, we still need a "View" button which requires interaction.

**Comment by ollytom** [comment]
uh sorry email replies can't do links or formatting...!!
Actually thinking about it now... there are now 2 buttons in the footer: Home and Save Dashboard. The dashboard is actually live updated in memory on almost every interaction (watch the JS console, very chatty!!). So in a sense doing a Save on exit would actually be the same interface to the user as a continuous save! Know what I mean?

**Comment by davekempe** [comment]
> uh sorry email replies can't do links or formatting...!! Actually thinking about it now... there are now 2 buttons in the footer: Home and Save Dashboard. The dashboard is actually live updated in memory on almost every interaction (watch the JS console, very chatty!!). So in a sense doing a Save on exit would actually be the same interface to the user as a continuous save! Know what I mean?

Not sure if you are agreeing with me about continuous save or not. But that is separate feature request anyway. The view button should exist regardless, as its a workflow thing.
