### ISSUE TITLE
When "Save Dashboard" fails, it fails silently, the user is not informed

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#128]
**Describe the bug**
When "Save Dashboard" is pushed, the browser sends a POST to a URL to save the config.  If the POST fails for any reason the user is not informed.

**To Reproduce**
1. Go to the edit URL of any dashboard
2. Change the permissions on the webserver or intermediate proxy to forbid POST
3. Push the "Save Dashboard" button
4. See no error

**Expected behavior**
- user informed that their save failed
- backend propagate errors which fail save to frontend
- After saving, load and compare with current to check the save is valid
- similar behaviour in case of DNS failure, timeout, etc.

**Desktop (please complete the following information):**
- confirmed on Linux/Windows Chrome/Firefox/Edge

**Comment by ollytom** [comment]
Yes!!

I can think of 2 easy ways to report error messages to the user:

1. render and redirect to an error page e.g. /500.html. Contents of the page include the error string from the backend.
2. Throw a standard javascript alert.

Option 1 isn’t too good because if there’s a short transient error the in-memory dashboard state is lost as we redirect to another page.

Option 2 only requires a single line change from `console.log` to `alert`:

```diff
    try {
        meerkat.saveDashboard(dashboard);
    } catch(err) {
-    	console.log(err.message);
+       alert(err.message);
    }
```

The tricky way is implementing a dismissable element in, say, the bottom right hand corner in bootsrap/react (see https://getbootstrap.com/docs/5.2/components/alerts/). That requires importing Bootstrap’s JS. Currently we only import a single CSS file. Not a big deal, it’s a really well maintained project, but it’s always nice to do without it if we can; one less thing to worry about.
