### ISSUE TITLE
Provide a "what matches" pop-up for host and service filters

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#23]
In GitLab by @matthew.palmer on Oct 10, 2020, 13:32

Icinga filters are somewhat fiddly, and it can sometimes be hard to figure out exactly what a given filter will match.  It would be useful if there was a button next to the host/service filter `<input>` element which ran the filter string currently in the box against the backend Icinga, and listed what hosts or services will match the filter (perhaps optionally with each object's status?).  That way users can "test" a filter before they commit to it, and also make sure they're not matching something they didn't want to (which could have disastrous consequences for dashboard accuracy).

**Comment by ollytom** [comment]
I think this is a good idea. But I don't think that we need to have this feature in Meerkat itself. Imagine for example an icinga search command in a shell:

	icingasearch 'match(host.name, "mail*.example.com")'

That would then print out the results of that filter expression.
Imagine also a toy web app, with a single `<input>` element to write a filter expression in. Click "submit" and it returns the results of the expression.

The issue is that icinga filters are a bit fiddly, not well documented, and there is no good tooling available to become familiar with the syntax.
Trying to solve this issue by adding a feature to Meerkat may be convenient to some in the short term. But we need to also keep in mind maintenance issues (ongoing problem for Meerkat; not easy to maintain re: time and code quality). We'd also be missing out on an opportunity to provide an even clearer interface for working with filter expressions.
