### ISSUE TITLE
Links should default to open new tab

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#29]
target=_blank

**Comment by ollytom** [comment]
This feels like a lot of code to do something already provided by the browser.

Ironically there has been feedback of excessive tab/window proliferation.
Since the window/tab opening behaviour is set per dashboard by something other than the browser and user,
it surprises the user that some links open in new windows/tabs and others don't.

Would there be interest in a PR which restores default browser behaviour?
There would be a codebase simplicity win here.

If not, I'll close this issue as the behaviour to override default link behaviour per dashboard has been implemented already.

**Comment by ollytom** [comment]
No interest and the feature has been added already.
